name: chatbot
channels:
  - defaults
dependencies:
  - python=3.10
  - langchain
  - django
  - pip:
    - google-generativeai
    - pysqlite3
    - djangorestframework
    - django-cors-headers
    - python-dotenv
    - BeautifulSoup4
    - chromadb
